-- Enable Row Level Security (RLS) is recommended but disabled here for initial ease of use.
-- You can enable it later for better security.

-- 1. Roles Table
create table if not exists public.roles (
  id bigint generated by default as identity primary key,
  code text not null,
  name text not null,
  description text,
  status text default '사용',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Users Table
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  "userId" text not null unique,
  password text not null,
  name text not null,
  role text not null,
  phone text,
  email text,
  department text,
  status text default '사용',
  "smsReceive" text default '미수신',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Distributors Table
create table if not exists public.distributors (
  id bigint generated by default as identity primary key,
  name text not null,
  address text,
  "addressDetail" text,
  latitude text,
  longitude text,
  "managerName" text,
  "managerPhone" text,
  "managerEmail" text,
  memo text,
  status text default '사용',
  "managedMarkets" text[] default '{}',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Markets Table
create table if not exists public.markets (
  id bigint generated by default as identity primary key,
  "distributorId" bigint references public.distributors(id),
  name text not null,
  address text,
  "addressDetail" text,
  "zipCode" text,
  latitude text,
  longitude text,
  "managerName" text,
  "managerPhone" text,
  "managerEmail" text,
  memo text,
  "enableMarketSms" text default '사용',
  "enableStoreSms" text default '사용',
  "enableMultiMedia" text default '사용',
  "multiMediaType" text default '복합',
  "usageStatus" text default '사용',
  "enableDeviceFaultSms" text default '사용',
  "enableCctvUrl" text default '사용',
  "smsFire" text[] default '{}',
  "smsFault" text[] default '{}',
  "mapImage" text,
  status text default 'Normal',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Stores Table
create table if not exists public.stores (
  id bigint generated by default as identity primary key,
  "marketId" bigint references public.markets(id),
  name text not null,
  "managerName" text,
  "managerPhone" text,
  status text default '사용',
  "storeImage" text,
  memo text,
  "receiverMac" text,
  "repeaterId" text,
  "detectorId" text,
  mode text default '복합',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Fire Events Table (For Dashboard)
create table if not exists public.fire_events (
  id bigint generated by default as identity primary key,
  type text not null, -- 'fire' or 'fault'
  msg text not null,
  time timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 7. Storage Buckets (Optional: Run this if you want to set up storage via SQL, though usually done via UI)
-- insert into storage.buckets (id, name, public) values ('market-maps', 'market-maps', true);
-- insert into storage.buckets (id, name, public) values ('store-images', 'store-images', true);

-- 8. Initial Data (Optional)
insert into public.users ("userId", password, name, role, department, status, "smsReceive")
values ('admin', '12341234!', '관리자', '시스템관리자', '본사', '사용', '수신')
on conflict ("userId") do nothing;

insert into public.roles (code, name, description)
values 
('9999', '시스템관리자', '전체 관리 권한'),
('8000', '총판관리자', '총판 및 하위 시장 관리'),
('1000', '시장관리자', '특정 시장 관리')
on conflict do nothing;
