-- 1. 화재 이력 관리 테이블 (Fire Logs)
-- 기존 fire_events는 대시보드용 요약본이고, 이건 전체 이력용입니다.
create table if not exists public.fire_logs (
  id bigint generated by default as identity primary key,
  "marketId" bigint references public.markets(id),
  "marketName" text, -- 조인 성능을 위해 역정규화 혹은 View 사용 가능, 여기선 단순 텍스트 저장 가정
  "storeName" text, 
  "receiverMac" text,
  "repeaterId" text,
  "detectorId" text,
  "eventType" text not null, -- '화재', '고장', '복구'
  "eventDetail" text, -- 상세 내용 (예: 감지기 오작동 등)
  "occurrenceTime" timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. 기기 상태 관리 테이블 (Device Status Logs)
-- 주기적으로 들어오는 배터리 전압, 신호 강도 등 상태 기록
create table if not exists public.device_status_logs (
  id bigint generated by default as identity primary key,
  "receiverMac" text not null,
  "repeaterId" text,
  "detectorId" text,
  battery text, -- 예: 'Normal', 'Low', '3.7V'
  signal text, -- 예: 'Strong', 'Weak', '-80dBm'
  temperature text,
  smoke_value text,
  status text, -- 'Normal', 'Error'
  "loggedAt" timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. 데이터 수신 관리 테이블 (Data Reception Logs)
-- 수신기가 데이터를 보낸 '세션' 혹은 '패킷' 단위의 수신 이력
create table if not exists public.data_reception_logs (
  id bigint generated by default as identity primary key,
  "marketName" text,
  "receiverMac" text not null,
  "packetType" text, -- 'Heartbeat', 'Event', 'Command'
  "dataSize" int,
  "result" text, -- 'Success', 'ParseError'
  "receivedAt" timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. UART 통신 (Raw UART Logs)
-- 미들웨어가 TCP로 받은 원본 Raw Data를 그대로 저장 (디버깅용)
create table if not exists public.raw_uart_logs (
  id bigint generated by default as identity primary key,
  "direction" text default 'RX', -- 'RX'(수신), 'TX'(송신)
  "receiverMac" text, -- 식별 가능하다면 기록
  "rawData" text, -- Hex String 또는 Text
  "parsed" boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS 정책 (공용 읽기/쓰기 허용 - 데모용)
alter table public.fire_logs enable row level security;
alter table public.device_status_logs enable row level security;
alter table public.data_reception_logs enable row level security;
alter table public.raw_uart_logs enable row level security;

create policy "Public Select fire_logs" on public.fire_logs for select using ( true );
create policy "Public Insert fire_logs" on public.fire_logs for insert with check ( true );

create policy "Public Select device_status_logs" on public.device_status_logs for select using ( true );
create policy "Public Insert device_status_logs" on public.device_status_logs for insert with check ( true );

create policy "Public Select data_reception_logs" on public.data_reception_logs for select using ( true );
create policy "Public Insert data_reception_logs" on public.data_reception_logs for insert with check ( true );

create policy "Public Select raw_uart_logs" on public.raw_uart_logs for select using ( true );
create policy "Public Insert raw_uart_logs" on public.raw_uart_logs for insert with check ( true );
