-- 기존 detectors 테이블이 있다면 삭제하고 재생성 (구조 변경을 위해)
DROP TABLE IF EXISTS public.detector_stores;
DROP TABLE IF EXISTS public.detectors;

-- Detectors Table (화재감지기 관리 - 기본 정보)
create table if not exists public.detectors (
  id bigint generated by default as identity primary key,
  "marketId" bigint references public.markets(id),
  "receiverMac" text not null,
  "repeaterId" text not null, -- '01' ~ '20'
  "detectorId" text not null, -- '01' ~ '20'
  mode text default '복합', -- 복합, 열, 연기
  "cctvUrl" text,
  "usageStatus" text default '사용',
  "smsList" text[] default '{}',
  memo text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Junction Table for Multiple Stores (감지기-상가 다대다 연결)
create table if not exists public.detector_stores (
  id bigint generated by default as identity primary key,
  "detectorId" bigint references public.detectors(id) on delete cascade,
  "storeId" bigint references public.stores(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique("detectorId", "storeId") -- 중복 매핑 방지
);

-- RLS Policies
alter table public.detectors enable row level security;
alter table public.detector_stores enable row level security;

-- Policies for detectors
create policy "Public Select detectors" on public.detectors for select using ( true );
create policy "Public Insert detectors" on public.detectors for insert with check ( true );
create policy "Public Update detectors" on public.detectors for update using ( true );
create policy "Public Delete detectors" on public.detectors for delete using ( true );

-- Policies for detector_stores
create policy "Public Select detector_stores" on public.detector_stores for select using ( true );
create policy "Public Insert detector_stores" on public.detector_stores for insert with check ( true );
create policy "Public Update detector_stores" on public.detector_stores for update using ( true );
create policy "Public Delete detector_stores" on public.detector_stores for delete using ( true );
