-- 1. Common Codes Table (공통코드 관리)
create table if not exists public.common_codes (
  id bigint generated by default as identity primary key,
  code text not null,          -- 공통코드
  name text not null,          -- 공통코드명
  description text,            -- 공통코드 상세
  "groupCode" text,            -- 공통그룹코드
  "groupName" text,            -- 공통그룹코드명
  status text default '사용',   -- 사용여부
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. RLS Policies
alter table public.common_codes enable row level security;

create policy "Public Select common_codes" on public.common_codes for select using ( true );
create policy "Public Insert common_codes" on public.common_codes for insert with check ( true );
create policy "Public Update common_codes" on public.common_codes for update using ( true );
create policy "Public Delete common_codes" on public.common_codes for delete using ( true );

-- 3. Insert Menu Item (시스템 관리 > 공통코드 관리)
-- 기존 메뉴 SQL 실행 후라고 가정하고, 롤 관리(70)와 메뉴 관리(80) 사이에 넣습니다.
-- parentId = 2 (시스템 관리)
INSERT INTO public.menus ("parentId", label, path, icon, "sortOrder", "isVisiblePc", "isVisibleMobile")
VALUES (2, '공통코드 관리', '/common-codes', 'List', 75, true, false);
