-- Stores Table (상가 관리)
create table if not exists public.stores (
  id bigint generated by default as identity primary key,
  "marketId" bigint references public.markets(id),
  name text not null,
  "managerName" text,
  "managerPhone" text,
  status text default '사용',
  "storeImage" text,
  memo text,
  "receiverMac" text,
  "repeaterId" text,
  "detectorId" text,
  mode text default '복합',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);