-- 1. Data Reception Table (데이터 수신 관리)
create table if not exists public.data_reception (
  id bigint generated by default as identity primary key,
  "marketName" text,
  "logType" text, -- 로그유형 (예: 62)
  "receiverId" text, -- 수신기 (예: 0909)
  "repeaterId" text, -- 중계기 (예: 03)
  "receivedData" text, -- 수신데이터 (Long Hex String)
  "commStatus" text, -- 감지기통신상태 (Long Hex String)
  "batteryStatus" text, -- 감지기배터리상태 (Long Hex String)
  "chamberStatus" text, -- 감지기챔버상태 (Long Hex String)
  "registeredAt" timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. RLS Policies
alter table public.data_reception enable row level security;

-- Drop existing policies to prevent errors on re-run
DROP POLICY IF EXISTS "Public Select data_reception" ON public.data_reception;
DROP POLICY IF EXISTS "Public Insert data_reception" ON public.data_reception;
DROP POLICY IF EXISTS "Public Update data_reception" ON public.data_reception;
DROP POLICY IF EXISTS "Public Delete data_reception" ON public.data_reception;

-- Create policies
create policy "Public Select data_reception" on public.data_reception for select using ( true );
create policy "Public Insert data_reception" on public.data_reception for insert with check ( true );
create policy "Public Update data_reception" on public.data_reception for update using ( true );
create policy "Public Delete data_reception" on public.data_reception for delete using ( true );

-- 3. Menu Item (Data Management > Data Reception Management)
-- Update existing menu label if it exists (to fix spacing)
UPDATE public.menus SET label = '데이터 수신 관리' WHERE path = '/data-reception';

-- Insert if not exists
INSERT INTO public.menus ("parentId", label, path, "sortOrder", "isVisiblePc", "isVisibleMobile")
SELECT 4, '데이터 수신 관리', '/data-reception', 30, true, true
WHERE NOT EXISTS (SELECT 1 FROM public.menus WHERE path = '/data-reception');

-- 4. Initial Mock Data (If empty)
INSERT INTO public.data_reception ("marketName", "logType", "receiverId", "repeaterId", "receivedData", "commStatus", "batteryStatus", "chamberStatus", "registeredAt") 
SELECT '안양 남부시장', '62', '0909', '03', 'AA4D4300156233340909300309090301190000000000', '00000000000000000000', '00000000000000000000', '00000000000000000000', '2026-01-21 10:10:03.0'
WHERE NOT EXISTS (SELECT 1 FROM public.data_reception LIMIT 1);